### ISSUE TITLE
1 node setup with mongo 3.4.4 fails to rs.initiate()

### ISSUE THREAD

**Issue by tjhall13** [aws-quickstart/quickstart-mongodb#14] opened 2017-05-24 18:48 UTC
With mongo 3.4.4 rs.initiate() fails. rs.initiate() should be called with a parameter to explicitly set up the replica.

Error:
{
	"info2" : "no configuration specified. Using a default configuration for the set",
	"me" : "ip-10-1-17-132:27017",
	"ok" : 0,
	"errmsg" : "No host described in new configuration 1 for replica set s0 maps to this node",
	"code" : 93,
	"codeName" : "InvalidReplicaSetConfig"
}

**Comment by tjhall13** [comment] 2017-05-24 19:17
manually running this mongo function on my instance directly is a work around:
`rs.initiate({ _id: 's0', version: 1, members: [{ _id: 1, host: '10.1.17.132:27017', priority: 10 }] })`

**Comment by vsnyc** [comment] 2017-06-29 14:25
Thank you for reporting this, the issue is now fixed.

**Closed as completed by vsnyc** 2017-06-29 14:25 UTC
