### ISSUE TITLE
Accessing database using elastic ip

### ISSUE THREAD

**Issue by kpiyush17** [aws-quickstart/quickstart-mongodb#49] opened 2020-04-15 09:55 UTC
Hi,

I have created the mongodb cluster using cloud formation templates. Now, I want to access the db from the internet. For that, I have added an elastic IP to all 3 nodes. I also added my public IP to allow inbound rules in the security group. But I am not able to access the database using the elasticIP:27017.

What could be the problem?

Thanks

**Comment by vsnyc** [comment] 2020-04-15 14:31
By default, the MongoDB cluster is created in private subnets and the route tables don't allow for inbound internet access. The outbound access is through the NAT Gateway, see [this](https://github.com/aws-quickstart/quickstart-aws-vpc/blob/master/templates/aws-vpc.template#L2276-L2288).

What you're trying is not a recommended best practice, but if you are doing it only for testing, you can deploy this in two steps.
1. Launch the [VPC Quick Start](https://aws.amazon.com/quickstart/architecture/vpc/) to setup the VPC spanning three Availability Zones.
2. Use the **Deploy into your existing VPC** link in the [MongoDB quick start]( https://aws.amazon.com/quickstart/architecture/mongodb/) to setup the MongoDB cluster. In the CloudFormation console, when you are asked for *Primary Node Subnet*, *Secondary0 Node Subnet* and *Secondary1 Node Subnet* parameters, you can pass in the public subnet IDs of the VPC instead of the default behavior of choosing private subnet IDs. Thus, all your MongoDB instances will have public IP addresses and can be reached from the internet as long as the security groups allow.

**Comment by kpiyush17** [comment] 2020-04-15 14:35
@vsnyc 

Thanks for the reply. I will try the given approach. Actually our requirement includes accessing the database from multiple regions, that's why we need outside access.

**Comment by kpiyush17** [comment] 2020-04-15 15:52
@vsnyc 

I tried the public subnet way and I am able to connect it through the subnet. Also, while updating the subnet, I have to change the replica set hosts to public IPs instead of private IPs to make it work. 
This process changes the primary node. 
After connecting to the mongodb, I ran `db.stats()`, and getting the following output:
```
{
	"db" : "test",
	"collections" : 0,
	"views" : 0,
	"objects" : 0,
	"avgObjSize" : 0,
	"dataSize" : 0,
	"storageSize" : 0,
	"numExtents" : 0,
	"indexes" : 0,
	"indexSize" : 0,
	"fileSize" : 0,
	"fsUsedSize" : 0,
	"fsTotalSize" : 0,
	"ok" : 1,
	"operationTime" : Timestamp(1586965026, 1),
	"$clusterTime" : {
		"clusterTime" : Timestamp(1586965026, 1),
		"signature" : {
			"hash" : BinData(0,"kCyUG9OXbCU0kfNWRQsPSk2tdTg="),
			"keyId" : NumberLong("6815899806381113346")
		}
	}
}
```
I am not sure, why fsTotalSize is showing 0. Need some help on this?

**Comment by vsnyc** [comment] 2020-04-15 19:59
I wonder if it because the DB was just initialized and no actions were done. Is it reproducible? What happens if you run the following commands in sequence.
```
db.auth("admin", "YourAdminPassword")
show databases
db.stats()
```

I'm seeing a non-zero value.
```
s0:PRIMARY> use admin
switched to db admin
s0:PRIMARY> db.auth("admin", "xxxxxxxx")
1
s0:PRIMARY> show databases
admin   0.000GB
config  0.000GB
local   0.000GB
s0:PRIMARY> db.stats()
{
	"db" : "admin",
	"collections" : 3,
	"views" : 0,
	"objects" : 5,
	"avgObjSize" : 117.4,
	"dataSize" : 587,
	"storageSize" : 49152,
	"numExtents" : 0,
	"indexes" : 4,
	"indexSize" : 65536,
	"fsUsedSize" : 837308416,
	"fsTotalSize" : 804913152000,
	"ok" : 1,
	"operationTime" : Timestamp(1586980599, 1),
	"$clusterTime" : {
		"clusterTime" : Timestamp(1586980599, 1),
		"signature" : {
			"hash" : BinData(0,"9civI2vzWFyq7rz17vdlQ77jVQs="),
			"keyId" : NumberLong("6816011088983752705")
		}
	}
}
```

**Comment by kpiyush17** [comment] 2020-04-16 16:24
@vsnyc

Yes switching to admin lets me see the `totalSize`. Thanks for that.

So, If I want to install mongodb enterprise instead of community. Can I do that with the template? Same goes for the version, the template has max version of 4.0 of mongodb, I am looking for 4.2.

Also, in the template there is option of choosing replica set between 1 or 3. So choosing 1 will install a standalone server with replica set enabled?

**Comment by vsnyc** [comment] 2020-04-16 17:05
> So, If I want to install mongodb enterprise instead of community. Can I do that with the template? 

This Quick Start supports the community version, but you should be able to take the code and make it work with the enterprise version. We have a contributor's guide that describes the process you need to follow for [customizing the Quick Start][1].

> Same goes for the version, the template has max version of 4.0 of mongodb, I am looking for 4.2.

All quick starts are community supported. Let me know if you would be interested in making the update to support 4.2 and create a pull request. I've opened a new issue: https://github.com/aws-quickstart/quickstart-mongodb/issues/50  for this.

> Also, in the template there is option of choosing replica set between 1 or 3. So choosing 1 will install a standalone server with replica set enabled?

If I recall correctly, the installation behavior changed after version 3.4, see issue: https://github.com/aws-quickstart/quickstart-mongodb/issues/14. So yes, the installation will be like a replica set with 1 member.

I'm resolving this ticket, please open a new one if you have an unrelated topic to discuss. Makes it easier for people to search for issues.

[1]: https://aws-quickstart.github.io/option1.html

**Closed as completed** 2020-04-16 17:06 UTC
