### ISSUE TITLE
Getting a Secondary1NodeSubnet template fail with default settings.

### ISSUE THREAD

**Issue by adanklefsensection** [aws-quickstart/quickstart-mongodb#25] opened 2018-02-28 19:50 UTC
Deploying in Ohio region with 3 AZ, changing size from 400 to 25; everything else is default. Getting:

Parameter 'Secondary1NodeSubnet' must match pattern subnet-[0-9a-z]{8}

**Comment by vsnyc** [comment] 2018-02-28 19:53
What was the id of the Secondary1NodeSubnet that you selected?

**Comment by adanklefsensection** [comment] 2018-02-28 19:55
![image](https://user-images.githubusercontent.com/32719791/36809901-30d1df94-1c7e-11e8-8ca1-78681ec1cb30.png)

**Comment by adanklefsensection** [comment] 2018-02-28 19:58
Used the 'Quickstart for new VPC here' 

https://docs.aws.amazon.com/quickstart/latest/mongodb/step2.html

**Comment by vsnyc** [comment] 2018-02-28 20:01
I see. Do you happen to have the stack still up? If you go to the nested VPCStack in CloudFormation console and look at the Outputs tab, what is the value of PrivateSubnet2AID and PrivateSubnet3AID?

**Comment by vsnyc** [comment] 2018-02-28 20:18
This is likely happening because the AWS account is opted in for [longer resource ids](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resource-ids.html). I'll check in a fix and comment when the issue is resolved.
Thanks for reporting this!

**Comment by adanklefsensection** [comment] 2018-02-28 20:25
Very awesome, that's probably exactly what it is. I did opt in for longer resource ids. Good looking out!

**Comment by vsnyc** [comment] 2018-02-28 23:00
This is now fixed, please try again.

**Closed as completed by vsnyc** 2018-02-28 23:00 UTC

**Comment by adanklefsensection** [comment] 2018-03-01 17:59
Got further in the chain: 
![image](https://user-images.githubusercontent.com/32719791/36860815-3057e900-1d37-11e8-9b95-ce6f9123e3f8.png)
